name: Release
on:
  push:
    branches:
      - master
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  release:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn run build
      - name: Create Release Pull Request or Publish to yarn
        uses: changesets/action@v1
        with:
          publish: yarn run release
          commit: "ci: release packages"
          title: "ci: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
